### ISSUE TITLE
RFC: Simplify the database schema

### ISSUE THREAD

**Issue by simlmx** [openclimatefix/pv-site-datamodel#48]
# Rationale
The database schema is rather complex, which has a real impact on development speed. The added complexity is meant to address future performance bottlenecks but I think we should wait for those challenges to arise and really understand them before fixing them.
In the meantime, I propose we simplify the schema to have something that is simpler and closer to our mental model of the data.

Another part of the code that I think we can simplify is the read/write functions defined in this repo. Using the slqlachemy `session` directly, or using a local helper function would simplify the code (no need for pydantic validation, pandas dataframes, etc.). The proposed simplified database schema would also make these functions less relevant.

# Implementation steps
- [x] Simplify the database schema
        #50
  - [x] Remove tables `datetime_interval` and `latest_forecast_values`
  - [x] Remove the need to do a `JOIN` to get forecast_values (i.e. have the `site_uuid` in `forecast_value` also)
  - [x] Remove `write` functions (move them to client repos when needed)
- [x] Update `pv-site-api` to use the new schema (this reads many tables; some of it uses the `read` functions which we have kept so that should make it simple)
        https://github.com/openclimatefix/pv-site-api/pull/42
- [x] Update `pv-site-production` to use the new schema (this writes the `Forecasts*` tables)
        https://github.com/openclimatefix/pv-site-production/pull/36
- [x] Update [`PvConsumer`][pvc] (the service that writes in the `Generation` table) 
        https://github.com/openclimatefix/PVConsumer/pull/52
- [x] https://github.com/openclimatefix/pv-site-datamodel/issues/4

CC @peterdudfield @devsjc 

[pvc]: https://github.com/openclimatefix/PVConsumer

**Comment by peterdudfield** [comment]
Could you leave the read function in here. This keeps the API code very simple and I think thats nice. 
For the write functions, do you mind leaving them for the moment. If you prefer to use a simple on in your repo then you can. 

For the tables, please keep `status` and `clients` too. So we just drop `datetime_interval` and `latest_forecast_value'

**Comment by peterdudfield** [comment]
Ill set up Alembic, but ive put it in here - #4

**Comment by simlmx** [comment]
All done!
